[versions]
minecraft = "1.20.1"
parchment = "2023.09.03"
architectury-api = "9.2.14"
fabric-loader = "0.18.4"
fabric-api = "0.92.6+1.20.1"
fabric-kotlin = "1.13.8+kotlin.2.3.0"
forge = "1.20.1-47.4.13"
kotlin-forge = "4.12.0"

# Plugins
loom = "1.13.463"
architectury-plugin = "3.4.162"
shadow = "9.2.2"
kotlin = "2.3.0"


[libraries]
minecraft = { group = "net.minecraft", name = "minecraft", version.ref = "minecraft" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }
fabric-kotlin = { group = "net.fabricmc", name = "fabric-language-kotlin", version.ref = "fabric-kotlin" }
architectury = { group = "dev.architectury", name = "architectury", version.ref = "architectury-api" }
architectury-fabric = { group = "dev.architectury", name = "architectury-fabric", version.ref = "architectury-api" }
architectury-forge = { group = "dev.architectury", name = "architectury-forge", version.ref = "architectury-api" }
forge = { group = "net.minecraftforge", name = "forge", version.ref = "forge" }
forge-kotlin = { group = "thedarkcolour", name = "kotlinforforge", version.ref = "kotlin-forge" }

# Plugin marker artifacts for build-logic
loom-plugin = { group = "dev.architectury.loom", name = "dev.architectury.loom.gradle.plugin", version.ref = "loom" }
architectury-plugin = { group = "architectury-plugin", name = "architectury-plugin.gradle.plugin", version.ref = "architectury-plugin" }
shadow-plugin = { group = "com.gradleup.shadow", name = "shadow-gradle-plugin", version.ref = "shadow" }
kotlin-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }


[plugins]
loom = { id = "dev.architectury.loom", version.ref = "loom" }
architectury = { id = "architectury-plugin", version.ref = "architectury-plugin" }
